config/routes.rb
Rails.application.routes.draw do
  get 'page/home'

  devise_for :users
  root 'welcome#index'
  get 'welcome/index'

  resources :expenses, only: %i[index create]
  resources :questions do
    member do
      post 'answer'
    end
  end
  resources :weight_records, only: %i[index create]
  # namespace :weight_records do
  #   get '/', action: :index
  #   post  '/', action: :create
  # end

end

app/models/answer.rb
# frozen_string_literal: true

class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :answer, optional: true

  validates :text, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expenses_item.rb
# frozen_string_literal: true

class ExpensesItem < ApplicationRecord
  belongs_to :user

  validates :item_name, presence: true
  validates :price, presence: true
end

app/models/question.rb
# frozen_string_literal: true

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers

  validates :content, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :answers
  has_many :expenses_items
  has_many :weight_records

  validates :name, presence: true
end

app/models/weight_record.rb
class WeightRecord < ApplicationRecord
  belongs_to :user

  validates :weight, presence: true
  validates :measuring_date, presence: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  #
  # def after_sign_in_path_for(resource)
  #   root_path
  # end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/expenses_controller.rb
# frozen_string_literal: true

class ExpensesController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @item = ExpensesItem.new
  end

  def create
    @item = ExpensesItem.new(item_params)
  end

  private

  def item_params
    params.require(:expenses_item).permit(:purchase_date, :item_name, :price).merge(user_id: current_user.id)
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[index show]

  def index
    questions = Question.all.order(created_at: 'DESC')
    respond_to do |format|
      format.html
      format.json { render json: questions, include: [:user] }
    end
  end

  def create
    question = Question.new(question_params)
    if question.save
      render json: { render: :index, status: :ok }
    else
      render json: { render: :index, status: :ng }
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = Answer.where(question_id: params[:id]).order(created_at: 'DESC')
    @answer = Answer.new
    respond_to do |format|
      format.html
      format.json
    end
  end

  def answer
    answer = Answer.new(answer_params)
    if answer.save
      render json: { status: :ok, id: answer_params[:question_id] }
    else
      render json: { status: :ng, id: answer_params[:question_id] }
    end
  end

  private

  def set_user
    @user = current_user
  end

  def question_params
    params.require(:question).permit(:title, :content).merge(user_id: current_user.id)
  end

  def answer_params
    params.require(:answer).permit(:text, :question_id).merge(user_id: current_user.id)
  end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:index]

  def index

  end

  private
  def set_user
    @user = current_user
  end
end

app/controllers/weight_records_controller.rb
class WeightRecordsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[index]

  def index
    records = WeightRecord.all.order(created_at: 'DESC')
    respond_to do |format|
      format.html
      format.json { render json: records, include: [:user] }
    end
  end

  def create
    record = WeightRecord.new(weight_params)
    if record.save
      render json: { render: :index, status: :ok }
    else
      render json: { render: :index, status: :ng }
    end
  end

  private

  def set_user
    @user = current_user
  end

  def weight_params
    params.require(:record).permit(:weight, :fat_percentage, :measuring_date).merge(user_id: current_user.id)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/expenses/index.html.erb
<h2>家計簿アプリ</h2>
<p><%= @user.name %></p>

<div id="index_js">
  <p>レシートの入力</p>
  <%= form_for(@item, url: {controller: 'expenses', action: 'create'}) do |f| %>
    <%= f.label :purchase_date %>
    <%= f.date_select :purchase_date %>

    <%= f.label :item_name %>
    <%= f.text_field :item_name %>

    <%= f.label :price %>
    <%= f.text_field :price %>

    <%= f.submit "登録" %>
  <% end %>
</div>
<div id="vue_area">
  <router-view></router-view>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyApp</title>
    <%= csrf_meta_tags %>
    <%#= javascript_pack_tag 'hello_vue' %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/weight_records.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StudyApp</title>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
</head>

<body>
<div id="<%= "#{controller.controller_name}-#{controller.action_name}" %>">
  <%= yield %>
</div>
</body>
</html>

app/views/page/home.html.erb
<h1>Page#home</h1>
<p>Find me in app/views/page/home.html.erb</p>
<div id="hello">
  <p>{{ message }}</p>
</div>

<%= javascript_pack_tag 'hello_vue' %>

app/views/questions/show.html.erb
<div id="vue_area">
  <router-view></router-view>
</div>

app/views/weight_records/index.html.erb
<app-header
  heading-text="体重計アプリ"
></app-header>
<input-record></input-record>
<line-chart></line-chart>
<%= javascript_pack_tag "weight_record/index" %>

app/views/welcome/index.html.erb
<h2>Welcom to YASAGORI Study Page</h2>
<% if user_signed_in? %>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "ログイン", new_user_session_path, class: 'post' %>
  <%= link_to "新規登録", new_user_registration_path, class: 'post' %>
<% end %>
<div>
  <%= link_to "質問箱へ", questions_path %>
</div>
<div>
  <%= link_to "家計簿アプリへ", expenses_path %>
</div>
<div>
  <%= link_to "体重計アプリへ", weight_records_path %>
</div>